### ISSUE TITLE
Create an Expense Splitter for Group Outings

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#14]
Develop an app that helps groups split expenses for events, keeping track of who owes what.

**Comment by kajal-jotwani** [comment]
can i work on this issue?

**Comment by rkt-1597** [comment]
@king04aman Can this issue be assigned to me?

**Comment by king04aman** [comment]
I've assigned @kajal-jotwani and @rkt-1597 to the issue — good luck, and I look forward to seeing your progress!

**Comment by rkt-1597** [comment]
Thanks @king04aman !
