### ISSUE TITLE
Implement OCR Tool for Image-to-Text Conversion

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#23]
Create a Python script that utilizes OCR libraries (e.g., Tesseract-OCR, Pytesseract) to extract text from images. The script should accept image files as input and output the extracted text. Ideal for document scanning and digitization applications.

**Comment by thugeyy712** [comment]
@king04aman Hello, I would like to work for you. Can you assign it to me please :< ?PLeaseeeeeeeeeeeeeeeee

**Comment by king04aman** [comment]
Assigned!! Happy Coding 🥳
