### ISSUE TITLE
Implement Real-Time Cryptocurrency Price Tracker

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#26]
Design a Python script to track real-time cryptocurrency prices using APIs like CoinGecko or CryptoCompare. The script should display current prices, price changes, and historical data.

Read issue #11 (Message for Hacktoberfest Contributors) before contributing.

**Comment by aafaris** [comment]
Hi @king04aman, I am keen to work on this. Could you please assign this to me? Thanks!

**Comment by thugeyy712** [comment]
@king04aman Hello, I would like to work for you. Can you assign it to me please :< ?

**Comment by king04aman** [comment]
Hi @aafaris , Assigned to you. Happy Coding 🥳
