### ISSUE TITLE
Develop Text Summarization Tool using NLP Libraries

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#32]
Build a Python script to summarize long texts into concise versions using NLP libraries (e.g., NLTK, TextRank). The script should output the summarized text.

**Comment by himanshumahajan138** [comment]
please assign NLP Related issues to me i can work around to solve them efficiently so please assign this to me

**Comment by king04aman** [comment]
Assigned!! Happy Coding 🥳
