### ISSUE TITLE
Tic-Tac-Toe AI using Minimax Algorithm

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#36]
Create a Python script using Pygame to build a Tic-Tac-Toe game with AI. Implement the Minimax algorithm to make optimal moves.

Read issue #11 (Message for Hacktoberfest Contributors) before contributing.

**Comment by Naumantamboli** [comment]
assign me this i want to work on this

**Comment by king04aman** [comment]
Assigned!! Happy Coding 🥳

**Comment by RashmitTopG** [comment]
I would also like to work on this.

**Comment by muhd360** [comment]
@king04aman is this issue closed???

**Comment by king04aman** [comment]
Hi @Naumantamboli ,

Just checking in on the assigned issue. Other contributors are waiting, so an update or ETA would be appreciated.

Thanks!

**Comment by Naumantamboli** [comment]
hi @king04aman ,the pull request has already been submitted and it will be completed once reviewed.

**Comment by king04aman** [comment]
Whoops, @Naumantamboli ! 😂 I completely overlooked your merged PR— I need to level up my observation skills! Thanks for your speedy work! 🎉
