### ISSUE TITLE
2D Platformer Game using Pygame

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#39]
Develop a Python script using Pygame to create a 2D platformer game. Implement player movement, jumping, and scoring features.

**Comment by nepal143** [comment]
please assign it to me I would like to work  on this

**Comment by king04aman** [comment]
Assigned!! Happy Coding 🥳

**Comment by nepal143** [comment]
Sorry for the delay; I was busy with my college file submissions.
😔😔

**Comment by king04aman** [comment]
Great work @nepal143!!
