### ISSUE TITLE
My Personal Journal - Capture Your Thoughts

### ISSUE THREAD

**Issue by king04aman** [king04aman/All-In-One-Python-Projects#49]
A simple application for users to maintain a daily journal. Features could include mood tracking, tagging entries, and searching past entries by date or keywords.

**Comment by konan625** [comment]
Can you assign this to me?

**Comment by king04aman** [comment]
Assigned!! Happy Contributing 🥳

**Comment by konan625** [comment]
@king04aman Please review the pr
